#!/bin/bash

: ${PREFIX:=ceph}
if [[ ! -z "$ETCDCTL_PEERS" ]]; then
	confd -confdir="/tpl.confd" -interval=60 -prefix="/$PREFIX/"
elif [[ ! -z "$CONSUL" ]]; then
	confd -backend consul -node $CONSUL -confdir="/tpl.confd" -interval=5 -prefix="/$PREFIX/"
else
  sleep 999
fi
